import Head from 'next/head'
import { FastForwardIcon } from '@heroicons/react/outline'

export default function Home() {
  return (
    <div className="container mx-auto">
      <div className="py-20 text-xl flex px-5 md:px-0">
        <FastForwardIcon className="h-20 l-20 text-blue-400 my-auto mr-5" />
        <div className="my-auto">
          <p className="mb-2 font-medium">Ready to start to find what you search ?</p>
          <p>Take it to the next level using our search engine to find informations about films, series or games!</p>
        </div>
      </div>
      <Head>
        <title>OMDb UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
